[SG-1022] Update min password requirements to 12 char
bitwarden/android pull request #2368
Opened 2023-02-14 00:27 UTC by BrandonM-Bitwarden

## Type of change
- [ ] Bug fix
- [x] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

## Code changes
Updates the minimum password length to 12. 

* **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-02-14 16:37 UTC, differsthecat submitted a review, later dismissed
LGTM 👍

2023-02-14 17:32 UTC, fedemkr commented on src/App/Resources/AppResources.resx
> +    <value>Master password must be at least 12 characters long.</value>
It'd be good to change this resource to have the number of characters as a parameter as in `YourMasterPasswordCannotBeRecoveredIfYouForgetItXCharactersMinimum`. So then when we need to update the number we just update the `Constants` file.
Something like:
```xml
<data name="MasterPasswordLengthValMessageX" xml:space="preserve">
    <value>Master password must be at least {0} characters long.</value>
</data>
<!--Or IMO even better for reading and knowing exactly what the message is when looking the code outside of this file-->
<data name="MasterPasswordMustBeAtLeastXCharactersLong" xml:space="preserve">
    <value>Master password must be at least {0} characters long.</value>
</data>
```

2023-02-15 17:54 UTC, fedemkr requested changes

2023-02-15 17:54 UTC, fedemkr commented on src/App/Resources/AppResources.resx
> +</root>
There should be a new line at the end of the file just in case

2023-02-16 14:15 UTC, fedemkr approved these changes

2023-02-16 18:15 UTC, merged