[PM-11649] Expired link services
bitwarden/android pull request #3863
Opened 2024-09-04 19:58 UTC by andrebispo5

## 🎟️ Tracking

[PM-11649](https://bitwarden.atlassian.net/browse/PM-11649) Email verification expired token service

## 📔 Objective

Consume api endpoint to verify if the token provided by email, during email verification flow, is still valid to use.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-09-04 22:23 UTC, david-livefront commented on app/src/main/java/com/x8bit/bitwarden/data/auth/datasource/network/service/IdentityServiceImpl.kt
> +                        codes = (400..499).toList(),
Do we actually want to catch all of the 400s?

2024-09-04 22:23 UTC, david-livefront commented on app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
> +                        return VerifyEmailTokenResult.Error
You do not need these `return`s

2024-09-04 22:24 UTC, david-livefront commented on app/src/main/java/com/x8bit/bitwarden/data/auth/repository/AuthRepositoryImpl.kt
> +                    if (it.message?.contains("Expired link", ignoreCase = true) == true) {
I just spoke to @dseverns-livefront about this. Stuff like this should be in the service.

2024-09-04 22:42 UTC, dseverns-livefront requested changes
<img src="https://media0.giphy.com/media/l36kU80xPf0ojG0Erg/giphy.gif"/>

Looks like some Jira wires got crossed: I think #3862 may be taking care of this, the main difference I am seeing is the wider range of 400s errors caught. Lets chat tomorrow and figure it out! 👍

2024-09-05 09:22 UTC, andrebispo5 commented
> ![](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966) [ ![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966) ](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966) [ ](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966)
> 
> Looks like some Jira wires got crossed: I think #3862 may be taking care of this, the main difference I am seeing is the wider range of 400s errors caught. Lets chat tomorrow and figure it out! 👍

Yup 

> ![](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966) [ ![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966) ](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966) [ ](https://camo.githubusercontent.com/0d4060d90d4e82937f382c171bd541be46acb0862d7036b7d14749ef73e4e4d8/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6c33366b553830785066306f6a47304572672f67697068792e676966)
> 
> Looks like some Jira wires got crossed: I think #3862 may be taking care of this, the main difference I am seeing is the wider range of 400s errors caught. Lets chat tomorrow and figure it out! 👍

Yup it is the same... Just added the wider range because it was like that on iOS but I don't think it is necessary. I'll close and link to #3862.

2024-09-05 09:22 UTC, closed without merging