QA-953: Adding testTag to elements in Add TOTP screen
bitwarden/android pull request #4160
Opened 2024-10-25 13:04 UTC by ifernandezdiaz

## 🎟️ Tracking

## 📔 Objective

This work is a subtask of [QA-947](https://bitwarden.atlassian.net/browse/QA-947), a story created to group all the native app views that contain elements without Automation IDs.
NOTE: Not all the elements will require an AutomationID. We are adding the ones we currently need so we can reduce the flakiness on some critical Mobile e2e tests

## 📸 Screenshots

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[QA-947]: https://bitwarden.atlassian.net/browse/QA-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-25 15:14 UTC, david-livefront commented on app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt
> +                    .testTag("EnterKeyManuallyButton"),
Please run the formatter

2024-10-25 19:33 UTC, SaintPatrck submitted a review, later dismissed

2024-10-25 19:46 UTC, david-livefront requested changes
Please make sure you apply the formatter before merging

2024-10-25 19:49 UTC, david-livefront commented on app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/manualcodeentry/ManualCodeEntryScreen.kt
> +                    .testTag("EnterKeyManuallyButton"),
This is still incorrect, it should be:

```kotlin
                modifier = Modifier
                    .padding(horizontal = 16.dp)
                    .testTag("EnterKeyManuallyButton"),
```

There is also a tutorial for setting up a macro for this in the [readme](https://github.com/bitwarden/android/blob/main/README.md#setup).

2024-10-28 14:18 UTC, david-livefront approved these changes

2024-10-28 14:55 UTC, merged